# before committing check this file here: https://lint.travis-ci.org/

language: python

git:
  quiet: true

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.9
          env: TOXENV=coverage
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
        - python: 3.8
          env: TOXENV=py38
        - python: 3.9
          env: TOXENV=py39
        - python: 3.9
          env: TOXENV=docs
        - python: 2.7
          env: TOXENV=pep8
        - python: 3.9
          env: TOXENV=pep8
        - python: 3.8
          env: TOXENV=packaging
#    uncomment and adjust if you want to allow some failures
#    allow_failures:
#        - python: 3.8
#          env: TOXENV=py38

sudo: false

install:
  - travis_wait ./.travis/install_linux.sh

script:
  - travis_wait tox --notest && travis_retry tox -- --forked
# in case all previous commands in script section succeeded, run deploy (if tag is present)
  - if [[ "$TRAVIS_TEST_RESULT" == "0" ]] && [[ $TOXENV == "packaging" ]]; then .travis/deploy_package.sh pypi ; fi

deploy:
  - provider: releases # deploy files to Github release page https://docs.travis-ci.com/user/deployment/releases/
    api_key: # encoded github token
      secure: sJCUpC/Igjwg98CX55newMpaUjXVv/hdQOi3oazOHJBxk4b2c8Re67to3YAttWu6546zMHWyfgAbgIUHq4cqUc71IbihlHwYCGIx756vT8qebLMQUHv+qtNllaXxrzfm9S3HIrNQG4KJfQOADYBqdXfLYccLWUCF6cTNi3ccWsHwxiHl3ekuCLOq58UnL1cF6PAv2ULGIrXIDWc80VgWH6TgtF8/GhZigCE5c8YkNRYReLf8O3ZgD+anunKLHmzwKnwVgikvjotZz4j9csmFRJotKGZeqgAk7Ux95PNlgM661RXSUiZxRwOlxEUPL/qEz7ExXB9FgNLbRnqhj83L1uueKDlvz2nTVa3wy5r80Q/bxeJ63evQu5rRMod8iKmQI1zZ5pwlQqrG0rt6dpL9nySf+80Gg9WT+wNvhxyyusbuNSe0Tgvg9BgLkXzrTX/4dSB5ERBXwbyUfCWAV8COExUONZeHAO8CACfJvi/ehDOERISFPIF+3uIhN+AuFfXwjk3edh1Kvxm+/Jt5NySujJPkCAadZ5PSJqBCwkGQRvDzrKGlGLDtpWNBvzBGfjlMbWtFLp8O/UNWBbQmdCLAlWfT7J0YtTp4s9ch4EPnTvaimsH0mWHkOv2FoYbLY82ArDW/jVwoF3zYlYDbyCT7cu7blfG5Zxbg4gyXnralUvw=
    file: "./release_files/*" # list of files to upload
    file_glob: true  # set to true if you want to use glob (* pattern) in file selection
    overwrite: true # overwrite the file if already uploaded
    skip_cleanup: true # keep generated files
    on:
      repo: DataMedSci/pymchelper 
      tags: true # fire only when tag applied (release being made)
      condition: $TOXENV == "packaging" && "$TRAVIS_TEST_RESULT" == "0" # fire for only one matrix element, if tests are OK
  - provider: pypi # upload pip package to pypi https://docs.travis-ci.com/user/deployment/pypi/
    username: "__token__"
    distributions: sdist bdist_wheel
    skip_cleanup: true
    skip_upload_docs: true
    password:
      secure: J5DtX72Ixl52SFqhTuPXAWPhSEV0uaBycUg7gxzAy86AKF0iR1BfG5BotMnbw8owu6yAzhNH0j6hwnCi9bj545UeWt/SCT2oPqCZfyfYtR2abrCjSK5Vk9eenOlYn3Wle1EFoyCWA+9FtA0bJ8MP/IPZdPPYloxk05+iCvsfA+dLWK5/NBr8SJh0wNK4QBuuGNzNAkPCoaUI+YWpYzALUToXvWVg9PxtonmIzs2uvdcvWEa0267ejNNfB+lCyezePHElAFY1L4F70d1XDrFBk+kcr6dzwJzFtvsHdmmV0qcNf/JzO/2EGAukUqhTYmLFa0b4TjDb/1SsyCDIMdQcHaJF1sqow9WlfyiQTFO5hket88+EGr6m70k3gzxMiGiV5q9q7aOO825WeRpYkcG/9YvPhpllxaHolpLeQIbi27RCma1whWVrmdvhVqW82tabaTTer+TIltaYP5FDzbBgwcbsfifgmm3FIY/TSVtUAO5+0MMacI0so3u6gLbf9aAaciM9su7+vRu4/7r1mkvaVE2LO2cR22a/5bwkcDYkjB9R54fPZOZp6fpM3pRN1IKMintpgml+1cZaWZRpe5ysBrgV1Whm9F8Un2ekGcSWNtPDbOAbJYqHHOIO0032EwqYudv42PhqtymKQCTCB8i6bxjCf7FDdK0gBBGNHpP3t2U=
    on:
      repo: DataMedSci/pymchelper
      tags: true
      condition: $TOXENV == "packaging" && "$TRAVIS_TEST_RESULT" == "0"
