version: '3.3'

services:

  pyinstaller:
    build:
      context: .
      dockerfile: pyinstaller.Dockerfile
    #image: pyinstaller
    container_name: pyinstaller
    command: /opt/python39/bin/pip3 freeze

  producer:
    depends_on:
      - pyinstaller
    build:
      context: .
      dockerfile: producer.Dockerfile
    container_name: producer
#    command: ls -alh /app/dist/
    command: find /app/dist/ -type f -exec cp {} /data/ \;
    volumes:
      - type: volume
        source: data
        target: /data

  tester:
    depends_on:
      - producer
    image: ubuntu:16.04
    container_name: tester
    command: find /data/ -type f -exec {}  --help \;
    volumes:
      - type: volume
        source: data
        target: /data


volumes:
  data: